version: 2.1
orbs:
  slack: circleci/slack@3.4.2
  gh-pages: sugarshin/gh-pages@0.0.6
workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - stable
                - v0.3.3
                - sigmod2014contest
                - gh-pages

jobs:
  test:
    resource_class: xlarge
    working_directory: ~/ldbc/ldbc_snb_datagen
    machine:
      image: ubuntu-2004:202008-01

    steps:
      - checkout
      - run: |
          DEBIAN_FRONTEND=noninteractive
          sudo apt update
          sudo apt install -y openjdk-8-jdk zip
          sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-8-openjdk-amd64/bin/java 1
          sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/bin/java
          java -version
      - run: docker build . -t ldbc/spark
      - restore_cache:
          keys:
            - m2-dep-branch:{{ .Branch }}-pom:{{ checksum "pom.xml" }}-
            - m2-dep-branch:dev-pom:{{ checksum "pom.xml" }}-
            - m2-dep-branch:{{ .Branch }}-
            - m2-dep-branch:dev-
      - run: mvn -ntp clean test-compile assembly:assembly
      - save_cache:
          key: m2-dep-branch:{{ .Branch }}-pom:{{ checksum "pom.xml" }}-{{ epoch }}
          paths:
            - ~/.m2/repository   # maven deps
            - ~/.sbt/1.0/zinc    # scala compiler bridge
      - run: |
          # deploy CircleCI configuration provide 'filters' instructions (and prevent failed build on gh-pages)
          cp -r .circleci dist/
          # CsvBasic using 'interactive mode'
          sed 's/:1$/:0.003/g' params-csv-basic.ini > params.ini
          tools/docker-run.sh
          cp -r out/social_network dist/social_network-csv-basic
          zip -r dist/social_network-csv-basic.zip dist/social_network-csv-basic
          # CsvBasic using 'raw data' mode
          sed 's/:1$/:0.003/g' params-csv-basic-rawdata.ini > params.ini
          tools/docker-run.sh
          cp -r out/social_network dist/social_network-csv-basic-rawdata
          zip -r dist/social_network-csv-basic-rawdata.zip dist/social_network-csv-basic-rawdata
          # CsvComposite
          sed 's/:1$/:0.003/g' params-csv-composite.ini > params.ini
          tools/docker-run.sh
          cp -r out/social_network dist/social_network-csv-composite
          zip -r dist/social_network-csv-composite.zip dist/social_network-csv-composite
          # CsvMergeForeign
          sed 's/:1$/:0.003/g' params-csv-merge-foreign.ini > params.ini
          tools/docker-run.sh
          cp -r out/social_network dist/social_network-csv-merge-foreign
          zip -r dist/social_network-csv-merge-foreign.zip dist/social_network-csv-merge-foreign
          # CsvCompositeMergeForeign
          sed 's/:1$/:0.003/g' params-csv-composite-merge-foreign.ini > params.ini
          tools/docker-run.sh
          cp -r out/social_network dist/social_network-csv-composite-merge-foreign
          zip -r dist/social_network-csv-composite-merge-foreign.zip dist/social_network-csv-composite-merge-foreign
      - gh-pages/deploy:
          ssh-fingerprints: '60:8f:35:48:99:c0:ae:9f:71:6b:a9:66:19:21:95:7d'
      - slack/status
